version: '3.8'

services:
  web:
    image: django:local
    build:
      dockerfile: Dockerfile
      target: development_build
      context: .
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgis/postgis:13-3.1-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.local

volumes:
  postgres_data:
